エラーが出た場合通知を表示する
tomoki69386/AppStoreReviewParser pull request #14
Opened 2020-01-06 04:22 UTC by lits0ra

close #13

2020-01-06 04:48 UTC, tomokisun requested changes

2020-01-06 04:48 UTC, tomoki69386 commented on js/index.js
> +            count++
showPage後にカウント足しても意味ないんじゃないかな
next page = count
って表示するから

2020-01-06 04:49 UTC, tomoki69386 commented on js/index.js
> +            count++
このコードだとnext pageじゃなくてcurrent pageが表示されてることになる

2020-01-06 04:49 UTC, tomoki69386 commented on js/index.js
> +            count++
@lits0ra

2020-01-06 04:50 UTC, lits0ra commented on js/index.js
> +            count++
showPageの前に書くと、next page = 1の場合が表示されへんと思った

2020-01-06 04:50 UTC, lits0ra commented on js/index.js
> +            count++
あーでも、そっか。うーーん

2020-01-06 04:52 UTC, tomoki69386 commented on js/index.js
> +            count++
初期値を変えるか、next pageじゃなくてcurrent pageにするか、入れ替えるか

2020-01-06 06:03 UTC, tomoki69386 commented on js/index.js
> +        return
うそ、ネットで調べた情報は間違いだった。かなしい

2020-01-07 06:30 UTC, tomoki69386 commented
@lits0ra 
idが無効になると1に戻すのではなくて、表示ボタンを押せなくするのが良さそう。
何故なら連打すると同じページが複数回表示されることになってしまうから

2020-01-07 06:31 UTC, tomoki69386 commented
そしてそうすると、再度表示することが出来なくなるので、リセットボタンを実装するといいかも
ただ実装自体はリロードさせるだけでいい気もする

2020-01-07 06:33 UTC, closed without merging